### PR TITLE
add pagination feature

### LINKED ISSUE #5: Failing Test Case: test_get_movie_reviews_api_failure()
**Describe the bug**
Calling `get_movie_reviews()` returned `[]` instead of `None` when api request fails.

**To Reproduce**
1. call `get_movie_reviews()` with invalid movie id of tmdb api

**Expected behavior**
None as a return

### PR DESCRIPTION
**Pull request by lingjunliu**
- add pagination buttons to view predicted movie results
- remove unnecessary tmdb api requests to improve performance

- how to test:
  - select a movie "inception" and then click "predict"
  - pagination buttons and predicted movies will pop up.

Note: the pagination implementation is currently not considering original filtering functions. (will fix soon, maybe it's better to open an issue for that)

### CODE REVIEW

**Comment by kofiarkoh** [comment]
rebase your changes unto develop and let see if the checks passes, otherwise something may be broken

**Comment by lingjunliu** [comment]
> rebase your changes unto develop and let see if the checks passes, otherwise something may be broken

I just rebased and fixed all the failing tests.

**Comment by habib-itopa** [comment]
Looks good.

**Review by habib-itopa — APPROVED** [review]
Looks Good.

**Review by kofiarkoh — APPROVED** [review]
looks good

**Pull request merged**
